### ISSUE TITLE
How to build the project ?

### ISSUE THREAD

**Issue by sleroy** [HeskeyBaozi/hexo-generator-to-json#1]
I would like to add some features but you did not provide the way to compile and build the library ?

Can you help me ?

Thanks

**Comment by sleroy** [comment]
OK, I found. 

Simply writing 
  ̀tsc` or
 ̀tsc -p tsconfig.json`

Can you add it to your README ?

Best regards

**Comment by HeskeyBaozi** [comment]
nice suggestions.
